In [20]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import sklearn.linear_model as skt
import seaborn as sns

In [21]:
df = pd.read_csv("economic_index.csv")

In [22]:
df.head()

   Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0           0  2017     12           2.75                5.3         1464
1           1  2017     11           2.50                5.3         1394
2           2  2017     10           2.50                5.3         1357
3           3  2017      9           2.50                5.3         1293
4           4  2017      8           2.50                5.4         1256

In [23]:
df.drop(columns=["Unnamed: 0"] , axis=1).head()

   year  month  interest_rate  unemployment_rate  index_price
0  2017     12           2.75                5.3         1464
1  2017     11           2.50                5.3         1394
2  2017     10           2.50                5.3         1357
3  2017      9           2.50                5.3         1293
4  2017      8           2.50                5.4         1256

In [30]:
X=df.iloc[:,:-1]

In [29]:
X

    Unnamed: 0  year  month  interest_rate  unemployment_rate
1            1  2017     11           2.50                5.3
2            2  2017     10           2.50                5.3
3            3  2017      9           2.50                5.3
4            4  2017      8           2.50                5.4
5            5  2017      7           2.50                5.6
6            6  2017      6           2.50                5.5
7            7  2017      5           2.25                5.5
8            8  2017      4           2.25                5.5
9            9  2017      3           2.25                5.6
10          10  2017      2           2.00                5.7
11          11  2017      1           2.00                5.9
12          12  2016     12           2.00                6.0
13          13  2016     11           1.75                5.9
14          14  2016     10           1.75                5.8
15          15  2016      9           1.75                6.1
16          16  2016      8           1.75                6.2
17          17  2016      7           1.75                6.1
18          18  2016      6           1.75                6.1
19          19  2016      5           1.75                6.1
20          20  2016      4           1.75                5.9
21          21  2016      3           1.75                6.2
22          22  2016      2           1.75                6.2
23          23  2016      1           1.75                6.1

In [37]:
y=df.iloc[:,-1]

In [38]:
y

0     1464
1     1394
2     1357
3     1293
4     1256
5     1254
6     1234
7     1195
8     1159
9     1167
10    1130
11    1075
12    1047
13     965
14     943
15     958
16     971
17     949
18     884
19     866
20     876
21     822
22     704
23     719
Name: index_price, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.25 , random_state=42)

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
scaler=StandardScaler()

In [45]:
X_train = scaler.fit_transform(X_train)

In [46]:
X_test = scaler.transform(X_test)

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression()

In [47]:
model.fit(X , y)

LinearRegression()

In [48]:
model.coef_

array([-27.99343612,   2.34690939,  -0.16947654,  71.92225193,
        45.09618248])

In [49]:
model.coef_

array([-27.99343612,   2.34690939,  -0.16947654,  71.92225193,
        45.09618248])

In [50]:
y_predict=model.predict(X_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [51]:
y_predict

array([-3803.30105404, -3676.77430875, -3792.02913711, -3650.15776971,
       -3680.61046428, -3732.44894067, -3782.99925766, -3684.44661981,
       -3674.29572162, -3795.86529264, -3790.67156872, -3830.15414275,
       -3813.68850189, -3724.84603861, -3761.40930188, -3821.12426329,
       -3798.34387977, -3667.98097896])